# Generated by Django 5.2.6 on 2025-09-25 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('language_code', models.CharField(default='en-US', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('user', 'User Message'), ('bot', 'Bot Response')], max_length=10)),
                ('content', models.TextField()),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('response_time', models.FloatField(blank=True, help_text='Response time in seconds', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatsession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('crop_diseases', 'Crop Diseases'), ('pest_identification', 'Pest Identification'), ('fertilizer_recommendations', 'Fertilizer Recommendations'), ('weather_advice', 'Weather Advice'), ('soil_health', 'Soil Health'), ('general', 'General Agriculture')], max_length=50)),
                ('topic', models.CharField(max_length=200)),
                ('question_patterns', models.TextField(help_text='Common question patterns, separated by newlines')),
                ('answer', models.TextField()),
                ('language_code', models.CharField(default='en-US', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'topic'],
                'indexes': [models.Index(fields=['category'], name='chatbot_kno_categor_692142_idx'), models.Index(fields=['language_code'], name='chatbot_kno_languag_a48f4f_idx')],
            },
        ),
    ]
